# Generated by Django 3.0.4 on 2020-04-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200405_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='items_json',
        ),
    ]
