# Generated by Django 3.0.4 on 2020-04-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
